version: '3.3'

services:
  db:
    image: postgres:15.0-alpine
    ports: 
     - "5433:5433"
    volumes:
      - db_val:/var/lib/postgresql/data/
    env_file:
      - ./.env

  web:
    build: .
    restart: always
    ports:
     - "8000:8000"
    depends_on:
     - db

    env_file:
      - ./.env 

volumes:
  db_val:
